# arch
# Autogenerated from man page /bedrock/cross/man/man1/arch.1
complete -c arch -l help -d 'display this help and exit'
complete -c arch -l version -d 'output version information and exit AUTHOR Written by David MacKenzie and Kar…'

