# aseqnet
# Autogenerated from man page /bedrock/cross/man/man1/aseqnet.1
complete -c aseqnet -s p -d 'Specify the TCP port number or TCP service name'
complete -c aseqnet -s s -d 'Subscribe to the given address for read automatically'
complete -c aseqnet -s d -d 'Subscribe to the given address for write automatically'
complete -c aseqnet -s v -d 'Verbose mode'

