# axfer
# Autogenerated from man page /bedrock/cross/man/man1/axfer.1
complete -c axfer -s l -d ','
complete -c axfer -l list-devices -d ','
complete -c axfer -s L -d ','
complete -c axfer -l list-pcms -d 'are acknowledged as list subcommand'

