# btrfs-replace
# Autogenerated from man page /bedrock/cross/man/man8/btrfs-replace.8
complete -c btrfs-replace -s r
complete -c btrfs-replace -s f
complete -c btrfs-replace -s B
complete -c btrfs-replace -s 1

