# btrfs-scrub
# Autogenerated from man page /bedrock/cross/man/man8/btrfs-scrub.8
complete -c btrfs-scrub -s c -d and
complete -c btrfs-scrub -s n -d 'options.  Note that not all IO schedulers honor the ionice settings'
complete -c btrfs-scrub -s B
complete -c btrfs-scrub -s d
complete -c btrfs-scrub -s r
complete -c btrfs-scrub -s R
complete -c btrfs-scrub -s f
complete -c btrfs-scrub -s q

