# c89
# Autogenerated from man page /bedrock/cross/man/man1/c89.1
complete -c c89 -o pedantic -d 'Issue extra warnings defined by ANSI for use of non-ANSI features'
complete -c c89 -o pedantic-errors -d 'Issue errors instead of warnings that normally would be presented by pedantic'
complete -c c89 -o D_ANSI_SOURCE -d 'Tell the system header file set to use an ANSI-conformant "clean" namespace'

