# chfn
# Autogenerated from man page /bedrock/cross/man/man1/chfn.1
complete -c chfn -s f -l full-name -d 'Specify your real name'
complete -c chfn -s o -l office -d 'Specify your office room number'
complete -c chfn -s p -l office-phone -d 'Specify your office phone number'
complete -c chfn -s h -l home-phone -d 'Specify your home phone number'
complete -c chfn -s u -l help -d 'Display help text and exit'
complete -c chfn -s v -l version -d 'Display version information and exit'

