# chpst
# Autogenerated from man page /bedrock/cross/man/man8/chpst.8
complete -c chpst -s u -d setuidgid
complete -c chpst -s U -d envuidgid
complete -c chpst -s b -d 'argv0.  Run  prog with  argv0 as the 0th argument'
complete -c chpst -s e -d envdir
complete -c chpst -s / -d 'chroot.  Change the root directory to  root before starting R prog '
complete -c chpst -s n -d 'nice.  Add  inc to the  nice (2) value before starting R prog '
complete -c chpst -s l -d 'lock.  Open the file  lock for writing, and obtain an exclusive lock on it'
complete -c chpst -s L -d 'The same as -l, but fail immediately if  lock is locked by another process'
complete -c chpst -s m -d 'limit memory'
complete -c chpst -s d -d 'limit data segment.  Limit the data segment per process to  bytes bytes'
complete -c chpst -s o -d 'limit open files'
complete -c chpst -s p -d 'limit processes.  Limit the number of processes per uid to R n '
complete -c chpst -s f -d 'limit output size.  Limit the output file size to  bytes bytes'
complete -c chpst -s c -d 'limit core size.  Limit the core file size to  bytes bytes'
complete -c chpst -s v -d 'verbose.  Print verbose messages to standard error'
complete -c chpst -s P -d 'pgrphack.  Run  prog in a new process group'
complete -c chpst -s 0 -d 'Close standard input before starting R prog '
complete -c chpst -s 1 -d 'Close standard output before starting R prog '
complete -c chpst -s 2 -d 'Close standard error before starting prog '

