# chsh
# Autogenerated from man page /bedrock/cross/man/man1/chsh.1
complete -c chsh -s s -l shell -d 'Specify your login shell'
complete -c chsh -s l -l list-shells -d 'Print the list of shells listed in  /etc/shells and exit'
complete -c chsh -s h -l help -d 'Display help text and exit'
complete -c chsh -s v -l version -d 'Display version information and exit'

