# chwso
# Autogenerated from man page /bedrock/cross/man/man1/chwso.1
complete -c chwso -s i -d 'Invert wid Ns \\(cqs position in the window stack'
complete -c chwso -s l -d 'Put wid at the bottom of the window stack'
complete -c chwso -s r -d 'Put wid on top of the window stack'

