# cksum
# Autogenerated from man page /bedrock/cross/man/man1/cksum.1
complete -c cksum -l help -d 'display this help and exit'
complete -c cksum -l version -d 'output version information and exit AUTHOR Written by Q.  Frank Xia'

