# cspctl
# Autogenerated from man page /bedrock/cross/man/man1/cspctl.1
complete -c cspctl -s h -l help -d 'Display a short help'
complete -c cspctl -s c -d 'Select a card number.  Option defaults to 0'
complete -c cspctl -s f -d 'Select a function from microcode file.  Option defaults to 1'
complete -c cspctl -s d -d 'Optional microcode description string'

