# cvt
# Autogenerated from man page /bedrock/cross/man/man1/cvt.1
complete -c cvt -s v -l verbose -d 'Warn verbosely when a given mode does not completely correspond with CVT stan…'
complete -c cvt -s r -l reduced -d 'Create a mode with reduced blanking'

