# dd
# Autogenerated from man page /bedrock/cross/man/man1/dd.1
complete -c dd -l help -d 'display this help and exit'
complete -c dd -l version -d 'output version information and exit AUTHOR Written by Paul Rubin, David MacKe…'

