# deluge-gtk
# Autogenerated from man page /bedrock/cross/man/man1/deluge-gtk.1
complete -c deluge-gtk -s c -l config -d 'Set the config directory location. SS Logging Options'
complete -c deluge-gtk -s l -l logfile -d 'Output to specified logfile instead of stdout'
complete -c deluge-gtk -s L -l loglevel -d 'Set the log level (default is error):  none, info, warning, error, debug'
complete -c deluge-gtk -s q -l quiet -d 'Sets the log level to none, same as -L none'
complete -c deluge-gtk -l logrotate -d 'Enable logfile rotation, with optional maximum logfile size, default: 2M (Log…'
complete -c deluge-gtk -l profile -d 'Profile with cProfile.  Outputs to stdout unless a filename is specified  '
complete -c deluge-gtk -s V -l version -d 'Show program\'s version number and exit'
complete -c deluge-gtk -s h -l help -d 'Show help message and exit'

