# deluged
# Autogenerated from man page /bedrock/cross/man/man1/deluged.1
complete -c deluged -s c -l config -d 'Set the config directory location. SS Daemon Options'
complete -c deluged -s p -l port -d 'Port daemon will listen on, default is 58846'
complete -c deluged -s i -l interface -d 'Interface daemon will listen for bittorrent connections on, this should be an…'
complete -c deluged -s u -l ui-interface -d 'Interface daemon will listen for UI connections on, this should be an IP addr…'
complete -c deluged -s l -l logfile -d 'Output to specified logfile instead of stdout'
complete -c deluged -s L -l loglevel -d 'Set the log level (default is error):  none, info, warning, error, debug'
complete -c deluged -s q -l quiet -d 'Sets the log level to none, same as -L none'
complete -c deluged -l logrotate -d 'Enable logfile rotation, with optional maximum logfile size, default: 2M (Log…'
complete -c deluged -l profile -d 'Profile with cProfile.  Outputs to stdout unless a filename is specified  '
complete -c deluged -s P -l pidfile -d 'Pidfile to store the process id'
complete -c deluged -s d -l do-not-daemonize -d 'Do not daemonize (fork) this process'
complete -c deluged -s U -l user -d 'Change to this user on startup (Requires root)'
complete -c deluged -s g -l group -d 'Change to this group on startup (Requires root)  . SS Help Options'
complete -c deluged -s V -l version -d 'Show program\'s version number and exit'
complete -c deluged -s h -l help -d 'Show help message and exit'

