# deluge
# Autogenerated from man page /bedrock/cross/man/man1/deluge.1
complete -c deluge -s c -l config -d 'Set the config directory location'
complete -c deluge -s s -l set-default-ui -d 'Sets the default UI to be run when no UI is specified  . SS Logging Options'
complete -c deluge -s l -l logfile -d 'Output to specified logfile instead of stdout'
complete -c deluge -s L -l loglevel -d 'Set the log level (default is error):  none, info, warning, error, debug'
complete -c deluge -s q -l quiet -d 'Sets the log level to none, same as -L none'
complete -c deluge -l logrotate -d 'Enable logfile rotation, with optional maximum logfile size, default: 2M (Log…'
complete -c deluge -l profile -d 'Profile with cProfile.  Outputs to stdout unless a filename is specified  '
complete -c deluge -s V -l version -d 'Show program\'s version number and exit'
complete -c deluge -s h -l help -d 'Show help message and exit'

