# deluge-console
# Autogenerated from man page /bedrock/cross/man/man1/deluge-console.1
complete -c deluge-console -s c -l config -d 'Set the config directory location'
complete -c deluge-console -s d -l daemon -d 'Deluge daemon IP address to connect to (default 127. 0. 0. 1)'
complete -c deluge-console -s p -l port -d 'Deluge daemon port to connect to (default 58846)'
complete -c deluge-console -s U -l username -d 'Deluge daemon username to use when connecting'
complete -c deluge-console -s P -l password -d 'Deluge daemon password to use when connecting  . SS Logging Options'
complete -c deluge-console -s l -l logfile -d 'Output to specified logfile instead of stdout'
complete -c deluge-console -s L -l loglevel -d 'Set the log level (default is error):  none, info, warning, error, debug'
complete -c deluge-console -s q -l quiet -d 'Sets the log level to none, same as -L none'
complete -c deluge-console -l logrotate -d 'Enable logfile rotation, with optional maximum logfile size, default: 2M (Log…'
complete -c deluge-console -l profile -d 'Profile with cProfile.  Outputs to stdout unless a filename is specified  '
complete -c deluge-console -s V -l version -d 'Show program\'s version number and exit'
complete -c deluge-console -s h -l help -d 'Show help message and exit'

