# devlink-health
# Autogenerated from man page /bedrock/cross/man/man8/devlink-health.8
complete -c devlink-health -s V -d 'devlink health show [ {  DEV  |  DEV/PORT_INDEX  } reporter REPORTER  ]  devl…'

