# devlink-dpipe
# Autogenerated from man page /bedrock/cross/man/man8/devlink-dpipe.8
complete -c devlink-dpipe -s V -d 'devlink dpipe table show  DEV [   name TABLE_NAME  ] devlink dpipe table set …'

