# devlink-dev
# Autogenerated from man page /bedrock/cross/man/man8/devlink-dev.8
complete -c devlink-dev -s V
complete -c devlink-dev -s n -d 'devlink dev show [  DEV  ] devlink dev help devlink dev eswitch set DEV [ mod…'

