# devlink-sb
# Autogenerated from man page /bedrock/cross/man/man8/devlink-sb.8
complete -c devlink-sb -s V
complete -c devlink-sb -s n -d 'devlink sb show  [  DEV  [  sb SB_INDEX  ] ] devlink sb pool show  [  DEV  [ …'

