# devlink-port
# Autogenerated from man page /bedrock/cross/man/man8/devlink-port.8
complete -c devlink-port -s V
complete -c devlink-port -s n -d 'devlink port set  DEV/PORT_INDEX [  type  {  eth  |  ib  |  auto  } ] devlink…'

