# dot2gxl
# Autogenerated from man page /bedrock/cross/man/man1/dot2gxl.1
complete -c dot2gxl -s g -d 'The command name and input file extensions are ignored, the input is taken as…'
complete -c dot2gxl -s d -d 'The command name and input file extensions are ignored, the input is taken as…'
complete -c dot2gxl -s '?' -d 'Prints usage information and exits'
complete -c dot2gxl -s o -d 'If specified, the output will be written into the file outfile'

