# driverless
# Autogenerated from man page /bedrock/cross/man/man1/driverless.1
complete -c driverless -s h -l help -l version -d 'Show help page, including version number'
complete -c driverless -s v -s d -l debug -d 'Debug mode, verbose logging to stderr'
complete -c driverless -l std-ipp-uris -d 'Show URIS in standard form'

