# edgepaint
# Autogenerated from man page /bedrock/cross/man/man1/edgepaint.1
complete -c edgepaint -o accuracy -d 'accuracy with which to find the maximally different coloring for each node wi…'
complete -c edgepaint -o angle -d 'color two edges differently if their incidence angle is less than a degrees'
complete -c edgepaint -o random_seed -d 'random seed to use.  s must be an integer'
complete -c edgepaint -o lightness -d 'only applies for the "lab" color scheme: l1 and l2 must integers, with 0 <= l…'
complete -c edgepaint -o share_endpoint -d 'if this option is specified, edges that shares an node are not considered in …'
complete -c edgepaint -s o -d 'write output to file f (default: stdout)'
complete -c edgepaint -o color_scheme -d 'specifies the color scheme'
complete -c edgepaint -s v -d 'turns on verbose mode'
complete -c edgepaint -s '?' -d 'Print usage and exit'

