# envy24control
# Autogenerated from man page /bedrock/cross/man/man1/envy24control.1
complete -c envy24control -s c -d 'Use the card specified by card-number rather than the first card'
complete -c envy24control -s D -d 'Use the card specified by control-name rather than the first card, normally t…'
complete -c envy24control -s o -d 'Limit number of analog line outputs to display'
complete -c envy24control -s i -d 'Limit number of analog line inputs to display'
complete -c envy24control -s p -d 'Limit number of PCM outputs to display.   Default is 8'
complete -c envy24control -s s -d 'Limit number of SPDIF inputs/outputs to display.   Default is 2'
complete -c envy24control -s f -d 'From/to this file will envy24control read/write the alsactl settings'
complete -c envy24control -s v -d 'It is not possible to manage something (muting, volume levels)'
complete -c envy24control -s m -d 'Use MIDI controller values to control the Faders in the mixer view'
complete -c envy24control -s M -d 'Use an enhanced mapping from midi controller values to db sliders'
complete -c envy24control -s w -d 'Specify the initial width of the envy24control window'
complete -c envy24control -s t -d 'Using -t 1 enlarges the channel mixers to the same height as the digital mixer'

