# exo-open
# Autogenerated from man page /bedrock/cross/man/man1/exo-open.1
complete -c exo-open -l launch -d 'tries to launch the preferred application for a certain category, optionally …'
complete -c exo-open -s '?' -l help
complete -c exo-open -s v -l version
complete -c exo-open -l working-directory

