# f2fs_io
# Autogenerated from man page /bedrock/cross/man/man8/f2fs_io.8
complete -c f2fs_io -s d -d 'use direct I/O'
complete -c f2fs_io -s m -d 'use mmap for source file'
complete -c f2fs_io -s s -d 'use sendfile to transfer data get_cblocks [file] Get the number of compressed…'

