# factor
# Autogenerated from man page /bedrock/cross/man/man1/factor.1
complete -c factor -l help -d 'display this help and exit'
complete -c factor -l version -d 'output version information and exit AUTHOR Written by Paul Rubin, Torbjorn Gr…'

