# fc-scan
# Autogenerated from man page /bedrock/cross/man/man1/fc-scan.1
complete -c fc-scan -s f -d 'Format output according to the format specifier format'
complete -c fc-scan -s V -d 'Show version of the program and exit'
complete -c fc-scan -s h -d 'Show summary of options'

