# filefrag
# Autogenerated from man page /bedrock/cross/man/man8/filefrag.8
complete -c filefrag -s B -d 'Force the use of the older FIBMAP ioctl instead of the FIEMAP ioctl for testi…'
complete -c filefrag -s b -d 'Use  blocksize in bytes, or with [KMG] suffix, up to 1GB for output instead o…'
complete -c filefrag -s e -d 'Print output in extent format, even for block-mapped files'
complete -c filefrag -s k -d 'Use 1024-byte blocksize for output (identical to \'-b 1024\')'
complete -c filefrag -s s -d 'Sync the file before requesting the mapping'
complete -c filefrag -s v -d 'Be verbose when checking for file fragmentation'
complete -c filefrag -s x -d 'Display mapping of extended attributes'
complete -c filefrag -s X -d 'Display extent block numbers in hexadecimal format'

