# fish_key_reader
# Autogenerated from man page /bedrock/cross/man/man1/fish_key_reader.1
complete -c fish_key_reader -s c -l continuous -d 'o 2'
complete -c fish_key_reader -s h -l help -d 'o 2'
complete -c fish_key_reader -s v -l version

