# foomatic-kitload
# Autogenerated from man page /bedrock/cross/man/man8/foomatic-kitload.8
complete -c foomatic-kitload -s k -d 'option, where dirname is the toplevel directory of a foomatic driver "kit"'
complete -c foomatic-kitload -s d -d 'destdir is a prefix to prepend to the install path'

