# getpcaps
# Autogenerated from man page /bedrock/cross/man/man8/getpcaps.8
complete -c getpcaps -l help -l usage -d 'Displays usage information and exits'
complete -c getpcaps -l ugly -l legacy -d 'Displays output in a somewhat ugly legacy format'
complete -c getpcaps -l verbose -d 'Displays usage in a legacy-like format but not quite so ugly in modern defaul…'

