# gfind
# Autogenerated from man page /bedrock/cross/man/man1/gfind.1
complete -c gfind -s P -d 'Never follow symbolic links.   This is the default behaviour'
complete -c gfind -s L -d 'Follow symbolic links'
complete -c gfind -s H -d 'Do not follow symbolic links, except while processing the command line argume…'
complete -c gfind -s D -d 'Print diagnostic information; this can be helpful to diagnose problems with w…'
complete -c gfind -o Olevel -d 'Enables query optimisation'
complete -c gfind -o print -d 'is used (but you should probably consider using'
complete -c gfind -o print0 -d 'instead, anyway)'
complete -c gfind -s O -d 'must appear before the first path name, if at all.   A double dash'
complete -c gfind -o noleaf -d 'If you later use the'
complete -c gfind -o type -d 'predicate will always match against the type of the file that a symbolic link…'
complete -c gfind -o delete -d 'can give rise to confusing behaviour.  Using'
complete -c gfind -o lname -d and
complete -c gfind -o ilname -d 'predicates always to return false'
complete -c gfind -o maxdepth -d 'would prevent this)'
complete -c gfind -o newer -d 'will be dereferenced, and the timestamp will be taken from the file to which …'
complete -c gfind -o newerXY
complete -c gfind -o anewer -d and
complete -c gfind -o cnewer
complete -c gfind -o follow -d 'option has a similar effect to'
complete -c gfind -o name -d and
complete -c gfind -o regex -d 'are performed first.  2 Any'
complete -c gfind -o xtype -d 'tests are performed after any tests based only on the names of files, but bef…'
complete -c gfind -o fstype -d 'predicate and specify a filesystem type FOO which is not known (that is, pres…'
complete -c gfind -o false -d '3 At this optimisation level, the full cost-based query optimiser is enabled'
complete -c gfind -s o -d 'predicates which are likely to succeed are evaluated earlier, and for'
complete -c gfind -s a -d 'predicates which are likely to fail are evaluated earlier'
complete -c gfind -o empty -d 'test for example is true only when the current file is empty'
complete -c gfind -o depth -d 'option for example makes find traverse the file system in a depth-first order'
complete -c gfind -o regextype -d 'option for example is positional, specifying the regular expression dialect f…'
complete -c gfind -o prune -d or
complete -c gfind -o quit -d 'Actions which inhibit the default'
complete -c gfind -o exec
complete -c gfind -o execdir
complete -c gfind -o ok
complete -c gfind -o okdir
complete -c gfind -o fls
complete -c gfind -o fprint
complete -c gfind -o fprintf
complete -c gfind -o ls
complete -c gfind -o printf -d The
complete -c gfind -o daystart -d 'Measure times (for'
complete -c gfind -o amin
complete -c gfind -o atime
complete -c gfind -o cmin
complete -c gfind -o ctime
complete -c gfind -o mmin -d and
complete -c gfind -o mtime -d 'from the beginning of today rather than from 24 hours ago'
complete -c gfind -o iregex -d 'tests which occur later on the command line'
complete -c gfind -o warn -o nowarn -d 'Turn warning messages on or off'
complete -c gfind -s d -d 'A synonym for -depth, for compatibility with FreeBSD, NetBSD,  MacOS X and Op…'
complete -c gfind -o help -l help -d 'Print a summary of the command-line usage of find and exit'
complete -c gfind -o ignore_readdir_race -d 'Normally, find will emit an error message when it fails to stat a file'
complete -c gfind -o mindepth -d 'Do not apply any tests or actions at levels less than levels (a non-negative …'
complete -c gfind -o mount -d 'Don\'t descend directories on other filesystems.   An alternate name for'
complete -c gfind -o xdev -d 'for compatibility with some other versions of find '
complete -c gfind -o noignore_readdir_race -d 'Turns off the effect of'
complete -c gfind -o version -l version -d 'Print the find version number and exit'
complete -c gfind -o samefile -d 'allow comparison between the file currently being examined and some reference…'
complete -c gfind -o gid
complete -c gfind -o inum
complete -c gfind -o links
complete -c gfind -o size
complete -c gfind -o uid -d and
complete -c gfind -o used -d 'as +n for greater than n ,'
complete -c gfind -s n -d 'for less than n , n for exactly n .  Supported tests:'
complete -c gfind -o executable -d 'Matches files which are executable and directories which are searchable (in a…'
complete -c gfind -o perm -d 'test ignores'
complete -c gfind -o group -d 'File belongs to group gname (numeric group ID allowed)'
complete -c gfind -o iname -d Like
complete -c gfind -o ipath -d Like
complete -c gfind -o path -d 'but the match is case insensitive'
complete -c gfind -o iwholename -d 'See -ipath.   This alternative is less portable than'
complete -c gfind -o nogroup -d 'No group corresponds to file\'s numeric group ID'
complete -c gfind -o nouser -d 'No user corresponds to file\'s numeric user ID'
complete -c gfind -o mode -d 'All of the permission bits mode are set for the file'
complete -c gfind -o 000
complete -c gfind -o readable -d 'Matches files which are readable by the current user'
complete -c gfind -o 1M -d 'is not equivalent to'
complete -c gfind -o 1048576c -d 'The former only matches empty files, the latter matches files from 0 to 1,048…'
complete -c gfind -o true -d 'Always true'
complete -c gfind -o user -d 'File is owned by user uname (numeric user ID allowed)'
complete -c gfind -o wholename -d 'See -path.   This alternative is less portable than'
complete -c gfind -o writable -d 'Matches files which are writable by the current user'
complete -c gfind -o context -d '(SELinux only) Security context of the file matches glob pattern '
complete -c gfind -o fprint0 -d 'True; like'
complete -c gfind -s 0 -d 'option of xargs '
complete -c gfind -o not -d 'Same as ! expr , but not POSIX compliant'
complete -c gfind -o a+r -d 'have at least one write bit set ( -perm /222 or'
complete -c gfind -o or
complete -c gfind -o 'D	4.3.1'
complete -c gfind -o 'O	4.3.1'
complete -c gfind -o 'readable	4.3.0'
complete -c gfind -o 'writable	4.3.0'
complete -c gfind -o 'executable	4.3.0'
complete -c gfind -o 'regextype	4.2.24'
complete -c gfind -o 'execdir	4.2.12	BSD'
complete -c gfind -o 'okdir	4.2.12'
complete -c gfind -o 'samefile	4.2.11'
complete -c gfind -o 'H	4.2.5	POSIX'
complete -c gfind -o 'L	4.2.5	POSIX'
complete -c gfind -o 'P	4.2.5	BSD'
complete -c gfind -o 'delete	4.2.3'
complete -c gfind -o 'quit	4.2.3'
complete -c gfind -o 'd	4.2.3	BSD'
complete -c gfind -o 'wholename	4.2.0'
complete -c gfind -o 'iwholename	4.2.0'
complete -c gfind -o 'ignore_readdir_race	4.2.0'
complete -c gfind -o 'fls	4.0'
complete -c gfind -o 'ilname	3.8'
complete -c gfind -o 'iname	3.8'
complete -c gfind -o 'ipath	3.8'
complete -c gfind -o 'iregex	3.8' -d 'The syntax . B -perm +MODE was removed in findutils-4. 5. 12, in favour of '

