# git-for-each-repo
# Autogenerated from man page /bedrock/cross/man/man1/git-for-each-repo.1
complete -c git-for-each-repo -l config -d 'Use the given config variable as a multi-valued list storing absolute path na…'

