# git-sparse-checkout
# Autogenerated from man page /bedrock/cross/man/man1/git-sparse-checkout.1
complete -c git-sparse-checkout -l cone -d 'is provided, the core'
complete -c git-sparse-checkout -l stdin -d 'option is provided, the patterns are read from standard in as a newline-delim…'

