# git-multi-pack-index
# Autogenerated from man page /bedrock/cross/man/man1/git-multi-pack-index.1
complete -c git-multi-pack-index -l object-dir -d 'Use given directory for the location of Git objects'
complete -c git-multi-pack-index -l progress -d 'Turn progress on/off explicitly'
complete -c git-multi-pack-index -l batch-size -d 'argument is zero, then create a pack containing all objects referenced by the…'

