# git-credential-cache
# Autogenerated from man page /bedrock/cross/man/man1/git-credential-cache.1
complete -c git-credential-cache -l timeout -d 'Number of seconds to cache credentials (default: 900)'
complete -c git-credential-cache -l socket -d 'Use <path> to contact a running cache daemon (or start a new cache daemon if …'

