# git-bugreport
# Autogenerated from man page /bedrock/cross/man/man1/git-bugreport.1
complete -c git-bugreport -s o -l output-directory -d 'Place the resulting bug report file in <path> instead of the root of the Git …'
complete -c git-bugreport -s s -l suffix -d 'Specify an alternate suffix for the bugreport name, to create a file named gi…'

