# glibc-getent
# Autogenerated from man page /bedrock/cross/man/man1/glibc-getent.1
complete -c glibc-getent -o sservice -l serviceservice -d '\\" commit 9d0881aa76b399e6a025c5cf44bebe2ae0efa8af (glibc) Override all datab…'
complete -c glibc-getent -o sdatabase:service -d '--servicedatabase:service '
complete -c glibc-getent -s i -l no-idn -d '\\" commit a160f8d808cf8020b13bd0ef4a9eaf3c11f964ad (glibc) Disables IDN encod…'
complete -c glibc-getent -s '?' -l help -d 'Print a usage summary and exit'
complete -c glibc-getent -l usage -d 'Print a short usage summary and exit'
complete -c glibc-getent -s s -l service
complete -c glibc-getent -s V -l version -d 'Print the version number, license, and disclaimer of warranty for getent '

