# glibc-ldd
# Autogenerated from man page /bedrock/cross/man/man1/glibc-ldd.1
complete -c glibc-ldd -l version -d 'Print the version number of  ldd '
complete -c glibc-ldd -s v -l verbose -d 'Print all information, including, for example, symbol versioning information'
complete -c glibc-ldd -s u -l unused -d 'Print unused direct dependencies.  (Since glibc 2. 3. 4. )'
complete -c glibc-ldd -s d -l data-relocs -d 'Perform relocations and report any missing objects (ELF only)'
complete -c glibc-ldd -s r -l function-relocs -d 'Perform relocations for both data objects and functions, and report any missi…'
complete -c glibc-ldd -l help -d 'Usage information'

