# gnu-dc
# Autogenerated from man page /bedrock/cross/man/man1/gnu-dc.1
complete -c gnu-dc -l version -d 'Print out the version of \\*(dc that is being run and a copyright notice, then…'
complete -c gnu-dc -l help -d 'Print a usage message briefly summarizing these command-line options and the …'
complete -c gnu-dc -l expression -d 'Add the commands in  script to the set of commands to be run while processing…'
complete -c gnu-dc -s V
complete -c gnu-dc -s h
complete -c gnu-dc -s e
complete -c gnu-dc -s f
complete -c gnu-dc -l file -d 'Add the commands contained in the file script-file to the set of commands to …'

