# gnu-bc
# Autogenerated from man page /bedrock/cross/man/man1/gnu-bc.1
complete -c gnu-bc -s h -l help -d 'Print the usage and exit'
complete -c gnu-bc -s i -l interactive -d 'Force interactive mode'
complete -c gnu-bc -s l -l mathlib -d 'Define the standard math library'
complete -c gnu-bc -s w -l warn -d 'Give warnings for extensions to POSIX bc'
complete -c gnu-bc -s s -l standard -d 'Process exactly the POSIX bc language'
complete -c gnu-bc -s q -l quiet -d 'Do not print the normal GNU bc welcome'
complete -c gnu-bc -s v -l version -d 'Print the version number and copyright and quit'
complete -c gnu-bc -l '->1<---' -d '0 px(1)'

