# gpg-zip
# Autogenerated from man page /bedrock/cross/man/man1/gpg-zip.1
complete -c gpg-zip -s e -d 'Encrypt data'
complete -c gpg-zip -s d -d 'Decrypt data'
complete -c gpg-zip -s c -d 'Encrypt with a symmetric cipher using a passphrase'
complete -c gpg-zip -s s -d 'Make a signature.   See gpg'
complete -c gpg-zip -s r -d 'Encrypt for user id user.  See gpg'
complete -c gpg-zip -s u -d 'Use user as the key to sign with.   See gpg'
complete -c gpg-zip -l list-archive -d 'List the contents of the specified archive'
complete -c gpg-zip -s o -d 'Write output to specified file file'
complete -c gpg-zip -l gpg -d 'Use the specified command gpgcmd instead of gpg'
complete -c gpg-zip -l gpg-args -d 'Pass the specified options to gpg'
complete -c gpg-zip -l tar -d 'Use the specified command tarcmd instead of tar'
complete -c gpg-zip -l tar-args -d 'Pass the specified options to tar'
complete -c gpg-zip -l version -d 'Print version of the program and exit'
complete -c gpg-zip -l encrypt
complete -c gpg-zip -l decrypt
complete -c gpg-zip -l symmetric
complete -c gpg-zip -l cipher-algo
complete -c gpg-zip -l sign
complete -c gpg-zip -l recipient
complete -c gpg-zip -l local-user
complete -c gpg-zip -l output
complete -c gpg-zip -l help -d 'Display a brief help page and exit.  EXAMPLES'

