# gpgv
# Autogenerated from man page /bedrock/cross/man/man1/gpgv.1
complete -c gpgv -s v -d 'Gives more information during processing'
complete -c gpgv -s q -d 'Try to be as quiet as possible'
complete -c gpgv -l keyring -d 'Add file to the list of keyrings'
complete -c gpgv -l status-fd -d 'Write special status strings to the file descriptor n'
complete -c gpgv -l logger-fd -d 'Write log output to file descriptor n and not to stderr'
complete -c gpgv -l ignore-time-conflict -d 'GnuPG normally checks that the timestamps associated with keys and signatures…'
complete -c gpgv -l homedir -d 'Set the name of the home directory to dir'
complete -c gpgv -l verbose
complete -c gpgv -l quiet
complete -c gpgv -l weak-digest -d 'Treat the specified digest algorithm as weak'

