# groups
# Autogenerated from man page /bedrock/cross/man/man1/groups.1
complete -c groups -l help -d 'display this help and exit'
complete -c groups -l version -d 'output version information and exit AUTHOR Written by David MacKenzie and Jam…'

