# grub-mkrelpath
# Autogenerated from man page /bedrock/cross/man/man1/grub-mkrelpath.1
complete -c grub-mkrelpath -s '?' -l help -d 'give this help list'
complete -c grub-mkrelpath -l usage -d 'give a short usage message'
complete -c grub-mkrelpath -s V -l version -d 'print program version REPORTING BUGS Report bugs to <bug-grub@gnu. org>'

