# gtester-report
# Autogenerated from man page /bedrock/cross/man/man1/gtester-report.1
complete -c gtester-report -s h -l help -d 'print help and exit'
complete -c gtester-report -s v -l version -d 'print version information and exit'
complete -c gtester-report -s s -l subunit -d 'Output subunit.  Needs python-subunit'

