# gtk-encode-symbolic-svg
# Autogenerated from man page /bedrock/cross/man/man1/gtk-encode-symbolic-svg.1
complete -c gtk-encode-symbolic-svg -s o -l output -d 'Write png files to DIRECTORY instead of the current working directory'

