# gtk-builder-convert
# Autogenerated from man page /bedrock/cross/man/man1/gtk-builder-convert.1
complete -c gtk-builder-convert -l skip-windows -s w -d 'Convert everything but GtkWindow subclasses'
complete -c gtk-builder-convert -l target-version -s t -d 'Some widgets and properties are different between GTK+ versions 2. 0 and 3'
complete -c gtk-builder-convert -l root -s r -d 'Convert only the widget named name and its children'

