# gtk-update-icon-cache
# Autogenerated from man page /bedrock/cross/man/man1/gtk-update-icon-cache.1
complete -c gtk-update-icon-cache -l force -s f -d 'Overwrite an existing cache file even if it appears to be uptodate'
complete -c gtk-update-icon-cache -l ignore-theme-index -s t -d 'Don\\*(Aqt check for the existence of \\*(Aqindex'
complete -c gtk-update-icon-cache -l index-only -s i -d 'Don\\*(Aqt include image data in the cache'
complete -c gtk-update-icon-cache -l include-image-data -d 'Include image data in the cache'
complete -c gtk-update-icon-cache -l source -s c -d 'Output a C header file declaring a constant name with the contents of the ico…'
complete -c gtk-update-icon-cache -l quiet -s q -d 'Turn off verbose output'
complete -c gtk-update-icon-cache -l validate -s v -d 'Validate existing icon cache'

