# halt
# Autogenerated from man page /bedrock/cross/man/man8/halt.8
complete -c halt -s n -d 'Don\'t sync before reboot or halt'
complete -c halt -s f -d 'Force halt or reboot, don\'t call init 8.  This is dangerous !'
complete -c halt -s d -d 'Do not write the wtmp record'
complete -c halt -s w -d 'Just write the wtmp record'
complete -c halt -s B -d 'Just write the wtmp record, but for a boot'
complete -c halt -s h -d 'to put hard drives in standby mode'
complete -c halt -s i -d 'to shut down network interfaces'

