# hardlink
# Autogenerated from man page /bedrock/cross/man/man1/hardlink.1
complete -c hardlink -s c -l content -d 'Compare only the contents of the files being considered for consolidation'
complete -c hardlink -s f -l force -d 'Force hardlinking across file systems'
complete -c hardlink -s n -l dry-run -d 'Do not perform the consolidation; only print what would be changed'
complete -c hardlink -s v -l verbose -d 'Print summary after hardlinking.  The option may be specified more than once'
complete -c hardlink -s x -l exclude -d 'Exclude files and directories matching pattern from hardlinking'
complete -c hardlink -s h -l help -d 'Display help text and exit'
complete -c hardlink -s V -l version -d 'Display version information and exit'

