# hostname-coreutils
# Autogenerated from man page /bedrock/cross/man/man1/hostname-coreutils.1
complete -c hostname-coreutils -l help -d 'display this help and exit'
complete -c hostname-coreutils -l version -d 'output version information and exit AUTHOR Written by Jim Meyering'

