# hostid
# Autogenerated from man page /bedrock/cross/man/man1/hostid.1
complete -c hostid -l help -d 'display this help and exit'
complete -c hostid -l version -d 'output version information and exit AUTHOR Written by Jim Meyering'

