# icc2ps
# Autogenerated from man page /bedrock/cross/man/man1/icc2ps.1
complete -c icc2ps -s b -d 'Black point compensation (CRD only)'
complete -c icc2ps -s i -d 'Input profile: Generates Color Space Array (CSA)'
complete -c icc2ps -s o -d 'p Output profile: Generates Color Rendering Dictionary(CRD)'
complete -c icc2ps -s t -d 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute)'
complete -c icc2ps -s u -d 'Do NOT generate resource name on CRD'

