# icclink
# Autogenerated from man page /bedrock/cross/man/man1/icclink.1
complete -c icclink -s 8 -d 'Creates 8-bit devicelink'
complete -c icclink -s b -d 'Black point compensation'
complete -c icclink -s c -d 'Precission (0=LowRes, 1=Normal, 2=Hi-res).  [defaults to 1]'
complete -c icclink -s d -d 'Description text (quotes can be used)'
complete -c icclink -s h -d 'Show summary of options and examples'
complete -c icclink -s i -d 'Input profile (defaults to sRGB)'
complete -c icclink -s k -d 'Ink-limiting in % (CMYK only)'
complete -c icclink -s o -d 'Output devicelink profile.  [defaults to \'devicelink. icm\']'
complete -c icclink -s t -d 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute)'
complete -c icclink -s x -d 'Creatively, guess deviceclass of resulting profile'

