# idn2
# Autogenerated from man page /bedrock/cross/man/man1/idn2.1
complete -c idn2 -s h -l help -d 'Prints help and exits'
complete -c idn2 -s V -l version -d 'Prints version and exits'
complete -c idn2 -s d -l decode -d 'Decode an ACE name according to IDNA2008'
complete -c idn2 -s l -l lookup -d 'Encode to ACE according to IDNA2008 (the default)'
complete -c idn2 -s r -l register -d 'Registers a label'
complete -c idn2 -s T -l tr46t -d 'Enable TR#46 transitional processing'
complete -c idn2 -s N -l tr46nt -d 'Enable TR#46 non-transitional processing (default)'
complete -c idn2 -l no-tr46 -d 'Disable TR#46 processing'
complete -c idn2 -l usestd3asciirules -d 'Enable STD3 ASCII rules'
complete -c idn2 -l debug -d 'Prints debugging information'
complete -c idn2 -l quiet -d 'Silent operation.  Author Written by Simon Josefsson'

