# ignw
# Autogenerated from man page /bedrock/cross/man/man1/ignw.1
complete -c ignw -s r -d 'Reset wid Ns \\(cqs override_redirect value to 0, unignoring the window'
complete -c ignw -s s -d 'Set wid Ns \\(cqs override_redirect value to 1, ignoring the window'

