# ip-monitor
# Autogenerated from man page /bedrock/cross/man/man8/ip-monitor.8
complete -c ip-monitor -s t -o timestamp -d 'Prints timestamp before the event message on the separated line in format:   …'
complete -c ip-monitor -o ts -o tshort -d 'Prints short timestamp before the event message on the same line in format:  …'

