# irqtop
# Autogenerated from man page /bedrock/cross/man/man1/irqtop.1
complete -c irqtop -s o -l output -d 'Specify which output columns to print'
complete -c irqtop -s d -l delay -d 'Update interrupt output every  seconds intervals'
complete -c irqtop -s s -l sort -d 'Specify sort criteria by column name'
complete -c irqtop -s V -l version -d 'Display version information and exit'
complete -c irqtop -l help -d 'to get a list of all supported columns'
complete -c irqtop -s h -d 'Display help text and exit'

