# isosize
# Autogenerated from man page /bedrock/cross/man/man8/isosize.8
complete -c isosize -s x -l sectors -d 'Show the block count and block size in human-readable form'
complete -c isosize -s d -l divisor -d 'Only has an effect when'

