# iwlist
# Autogenerated from man page /bedrock/cross/man/man8/iwlist.8
complete -c iwlist -l version -d 'Display the version of the tools, as well as the recommended and current Wire…'
complete -c iwlist -l help -d 'Display short help message'

