# jpegicc
# Autogenerated from man page /bedrock/cross/man/man1/jpegicc.1
complete -c jpegicc -s b -d 'Black point compensation'
complete -c jpegicc -s c -d 'Precalculates transform'
complete -c jpegicc -s g -d 'Marks out-of-gamut colors on softproof'
complete -c jpegicc -s h -d 'Show summary of options and examples'
complete -c jpegicc -s i -d 'Input profile (defaults to sRGB)'
complete -c jpegicc -s m -d 'SoftProof intent'
complete -c jpegicc -s n -d 'Ignore embedded profile'
complete -c jpegicc -s p -d 'Soft proof profile'
complete -c jpegicc -s o -d 'p Output profile (defaults to sRGB)'
complete -c jpegicc -s q -d 'Output JPEG quality'
complete -c jpegicc -s t -d 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute)'
complete -c jpegicc -s v -d 'Verbose.  EXAMPLES'

