# kill
# Autogenerated from man page /bedrock/cross/man/man1/kill.1
complete -c kill -s s -l signal -d 'The signal to send.   It may be given as a name or a number'
complete -c kill -s l -l list -d 'Print a list of signal names, or convert the given signal number to a name'
complete -c kill -s L -l table -d 'Similar to -l, but it will print signal names and their corresponding numbers'
complete -c kill -s a -l all -d 'Do not restrict the command-name-to-PID conversion to processes with the same…'
complete -c kill -s p -l pid -d 'Only print the process ID (PID) of the named processes, do not send any signa…'
complete -c kill -l verbose -d 'Print PID(s) that will be signaled with  kill along with the signal'
complete -c kill -s q -l queue -d 'Send the signal using  sigqueue (3) rather than  kill (2)'
complete -c kill -l timeout -d 'Send a signal defined in the usual way to a process, followed by an additiona…'
complete -c kill -s 1 -d 'All processes with a PID larger than 1 are signaled'

