# libinput-analyze-touch-down-state
# Autogenerated from man page /bedrock/cross/man/man1/libinput-analyze-touch-down-state.1
complete -c libinput-analyze-touch-down-state -l help -d 'Print help'
complete -c libinput-analyze-touch-down-state -l use-st -d 'Use the single-touch BTN_TOOL_ bits instead of the slot state'

