# libinput-quirks
# Autogenerated from man page /bedrock/cross/man/man1/libinput-quirks.1
complete -c libinput-quirks -l data-dir -d 'Use the given directory as data directory for quirks files'
complete -c libinput-quirks -l help -d 'Print help'
complete -c libinput-quirks -l verbose -d 'Use verbose output, useful for debugging'

