# libinput-analyze-recording
# Autogenerated from man page /bedrock/cross/man/man1/libinput-analyze-recording.1
complete -c libinput-analyze-recording -l help -d 'Print help OUTPUT An example output for a tablet sequence is below'
complete -c libinput-analyze-recording -l --------------------------------------------------------------- -d '  0'

