# libinput-record
# Autogenerated from man page /bedrock/cross/man/man1/libinput-record.1
complete -c libinput-record -l help -d 'Print help'
complete -c libinput-record -l all -d 'Record all /dev/input/event* devices available on the system'
complete -c libinput-record -l autorestart -d 'Terminate the current recording after  s seconds of device inactivity'
complete -c libinput-record -l output-file -d 'Specifies the output file to use'
complete -c libinput-record -l grab -d 'Exclusively grab all opened devices'
complete -c libinput-record -l show-keycodes -d 'Show keycodes as-is in the recording'
complete -c libinput-record -s o
complete -c libinput-record -l with-libinput -d 'Record libinput events alongside device events.  THIS FEATURE IS EXPERIMENTAL'
complete -c libinput-record -l multiple

