# libinput
# Autogenerated from man page /bedrock/cross/man/man1/libinput.1
complete -c libinput -l help -d 'Print help and exit'
complete -c libinput -l version -d 'Print the version and exit COMMANDS'

