# libinput-measure-fuzz
# Autogenerated from man page /bedrock/cross/man/man1/libinput-measure-fuzz.1
complete -c libinput-measure-fuzz -l help -d 'Print help LIBINPUT Part of the libinput(1) suite'

