# libinput-measure-touchpad-size
# Autogenerated from man page /bedrock/cross/man/man1/libinput-measure-touchpad-size.1
complete -c libinput-measure-touchpad-size -l help -d 'Print help LIBINPUT Part of the libinput(1) suite'

