# libwacom-list-local-devices
# Autogenerated from man page /bedrock/cross/man/man1/libwacom-list-local-devices.1
complete -c libwacom-list-local-devices -l database -d 'Sets the data directory path to be used'

