# link
# Autogenerated from man page /bedrock/cross/man/man1/link.1
complete -c link -l help -d 'display this help and exit'
complete -c link -l version -d 'output version information and exit AUTHOR Written by Michael Stone'

