# lneato
# Autogenerated from man page /bedrock/cross/man/man1/lneato.1
complete -c lneato -s V -d 'Prints the version'
complete -c lneato -o lm -d 'Sets the layout mode.  The mode can be sync or async.  The default is async'
complete -c lneato -o el -d 'Sets the mesage level.  The lev can be 0 or 1.  The default is 0'

