# loadunimap
# Autogenerated from man page /bedrock/cross/man/man8/loadunimap.8
complete -c loadunimap -s o -d 'oldmap option is given, the old map is saved in the file specified'
complete -c loadunimap -s C -d option

