# login
# Autogenerated from man page /bedrock/cross/man/man1/login.1
complete -c login -s p -d 'Used by  getty (8) to tell  login not to destroy the environment'
complete -c login -s f -d 'Used to skip a login authentication'
complete -c login -s h -d 'Used by other servers (i. e'
complete -c login -s H -d 'Used by other servers (i. e'
complete -c login -l help -d 'Display help text and exit'
complete -c login -s V -l version -d 'Display version information and exit'

