# logname
# Autogenerated from man page /bedrock/cross/man/man1/logname.1
complete -c logname -l help -d 'display this help and exit'
complete -c logname -l version -d 'output version information and exit AUTHOR Written by FIXME: unknown'

