# lpmove
# Autogenerated from man page /bedrock/cross/man/man8/lpmove.8
complete -c lpmove -s E -d 'Forces encryption when connecting to the server'
complete -c lpmove -s U -d 'Specifies an alternate username'
complete -c lpmove -s h -d 'Specifies an alternate server'

