# lsirq
# Autogenerated from man page /bedrock/cross/man/man1/lsirq.1
complete -c lsirq -s n -l noheadings -d 'Don\'t print headings'
complete -c lsirq -s o -l output -d 'Specify which output columns to print'
complete -c lsirq -s s -l sort -d 'Specify sort criteria by column name'
complete -c lsirq -s J -l json -d 'Use JSON output format'
complete -c lsirq -s P -l pairs -d 'Produce output in the form of key="value" pairs'
complete -c lsirq -s V -l version -d 'Display version information and exit'
complete -c lsirq -l help -d 'to get a list of all supported columns'
complete -c lsirq -s h -d 'Display help text and exit.  AUTHORS'

