# lsw
# Autogenerated from man page /bedrock/cross/man/man1/lsw.1
complete -c lsw -s a -d 'List all windows'
complete -c lsw -s r -d 'Print the ID of the root window'
complete -c lsw -s o -d 'List windows whose override_redirect attribute is set to 1'
complete -c lsw -s u -d 'List unmapped (invisible) windows'

