# lua
# Autogenerated from man page /bedrock/cross/man/man1/lua.1
complete -c lua -s e -d 'execute statement R stat '
complete -c lua -s i -d 'enter interactive mode after executing R script '
complete -c lua -s l -d 'execute the equivalent of B name =require(\' name \') before executing R script '
complete -c lua -s v -d 'show version information'
complete -c lua -s E -d 'ignore environment variables'

