# mandoc-soelim
# Autogenerated from man page /bedrock/cross/man/man1/mandoc-soelim.1
complete -c mandoc-soelim -s C -d 'Recognise . so when not followed by a space character'
complete -c mandoc-soelim -s r -d 'Compatibility with GNU groff\'s mandoc-soelim soelim (does nothing)'
complete -c mandoc-soelim -s t -d 'Compatibility with GNU groff\'s mandoc-soelim soelim (does nothing)'
complete -c mandoc-soelim -s v -d 'Compatibility with GNU groff\'s mandoc-soelim soelim (does nothing)'
complete -c mandoc-soelim -s I -d 'This option specify directories where mandoc-soelim searches for files (both …'

