# mandoc-whatis
# Autogenerated from man page /bedrock/cross/man/man1/mandoc-whatis.1
complete -c mandoc-whatis -s a -d 'Instead of showing only the title lines, show the complete manual pages, just…'
complete -c mandoc-whatis -s C -d 'Specify an alternative configuration file in man. conf 5 format'
complete -c mandoc-whatis -s f -d 'Search for all words in expression in manual page names only'
complete -c mandoc-whatis -s k -d 'Support the full expression syntax.  It is the default for mandoc-whatis'
complete -c mandoc-whatis -s M -d 'Use the colon-separated path instead of the default list of paths searched fo…'
complete -c mandoc-whatis -s m -d 'Prepend the colon-separated paths to the list of paths searched for makewhati…'
complete -c mandoc-whatis -s O -d 'Show the values associated with the key outkey instead of the manual descript…'
complete -c mandoc-whatis -s S -d 'Restrict the search to pages for the specified machine 1 architecture'
complete -c mandoc-whatis -s s -d 'Restrict the search to the specified section of the manual'
complete -c mandoc-whatis -s i -d 'If term is a regular expression, it is evaluated case-insensitively'

