# mkinitrd
# Autogenerated from man page /bedrock/cross/man/man8/mkinitrd.8
complete -c mkinitrd -l version -d 'print info about the version'
complete -c mkinitrd -s v -l verbose -d 'increase verbosity level'
complete -c mkinitrd -s f -l force -d 'overwrite existing initramfs file'
complete -c mkinitrd -l with -d 'add the kernel module <module> to the initramfs'
complete -c mkinitrd -l preload -d 'preload the kernel module <module> in the initramfs before any other kernel m…'
complete -c mkinitrd -l nocompress -d 'do not compress the resulting image'
complete -c mkinitrd -l help -d 'print a help message and exit'

