# mkinitrd-suse
# Autogenerated from man page /bedrock/cross/man/man8/mkinitrd-suse.8
complete -c mkinitrd-suse -s R -l version -d 'print info about the version'
complete -c mkinitrd-suse -o 'k<kernel_list>' -d 'List of kernel images for which initrd files are created (relative to boot_di…'
complete -c mkinitrd-suse -o 'i<initrd_list>' -d 'List of file names (relative to boot_dir) for the initrd; positions have to m…'
complete -c mkinitrd-suse -o 'm<module_list>' -d 'Modules to include in initrd, defaults to INITRD_MODULES variable in /etc/sys…'
complete -c mkinitrd-suse -o 'f<feature_list>' -d 'Features to be enabled for the initrd'
complete -c mkinitrd-suse -o 'b<bootdir>' -d 'Boot directory, defaults to /boot, where the initrd is created'
complete -c mkinitrd-suse -o 'd<root_device>' -d 'Root device, defaults to the device from which the root_dir is mounted; overw…'
complete -c mkinitrd-suse -o 's<size>' -d 'Add splash animation and bootscreen to initrd'
complete -c mkinitrd-suse -o 'D_<interface>' -d 'Run dhcp on the specified interface (for example "eth0")'
complete -c mkinitrd-suse -o 'I_<interface>' -d 'Configure the specified interface statically'
complete -c mkinitrd-suse -o 'a_<acpi_dsdt>' -d 'Attach compiled ACPI DSDT (Differentiated System Description Table) to initrd'
complete -c mkinitrd-suse -o 'M_<map>' -d 'System. map file to use'
complete -c mkinitrd-suse -s B -d 'Don\'t run the update-bootloader(8) script after the initrd(s) have been creat…'
complete -c mkinitrd-suse -s A -d 'Create a so called "monster initrd" which includes all available features and…'
complete -c mkinitrd-suse -s v -l verbose -d 'increase verbosity level'
complete -c mkinitrd-suse -s L -d 'Disable logging to /var/log/YaST2/mkinitrd. log'
complete -c mkinitrd-suse -l help -d 'print a help message and exit'
complete -c mkinitrd-suse -s k
complete -c mkinitrd-suse -s i
complete -c mkinitrd-suse -s m
complete -c mkinitrd-suse -s f
complete -c mkinitrd-suse -s b
complete -c mkinitrd-suse -s d
complete -c mkinitrd-suse -s s
complete -c mkinitrd-suse -s D
complete -c mkinitrd-suse -s I
complete -c mkinitrd-suse -s a
complete -c mkinitrd-suse -s M

