# mmroff
# Autogenerated from man page /bedrock/cross/man/man1/mmroff.1
complete -c mmroff -s z -d and
complete -c mmroff -o rRef -d 'to collect all cross references and then to do the real processing when the c…'
complete -c mmroff -s x -d 'Just create the cross-reference file'

