# ndptool
# Autogenerated from man page /bedrock/cross/man/man8/ndptool.8
complete -c ndptool -s h -l help -d 'Print help text to console and exit'
complete -c ndptool -s v -l verbose -d 'Increase output verbosity'
complete -c ndptool -s t -l msg-type -d 'Specified message type'
complete -c ndptool -s i -l ifname -d 'Specified interface name'
complete -c ndptool -s U -l unsolicited -d 'Send Unsolicited NA'

