# nop
# Autogenerated from man page /bedrock/cross/man/man1/nop.1
complete -c nop -s p -d 'Produce no output - just check the input for valid DOT'
complete -c nop -s '?' -d 'Print usage information'

