# pam_timestamp_check
# Autogenerated from man page /bedrock/cross/man/man8/pam_timestamp_check.8
complete -c pam_timestamp_check -s k -d 'Instead of checking the validity of a timestamp, remove it'
complete -c pam_timestamp_check -s d -d 'Instead of returning validity using an exit status, loop indefinitely, pollin…'

