# pivot_root
# Autogenerated from man page /bedrock/cross/man/man8/pivot_root.8
complete -c pivot_root -s V -l version -d 'Display version information and exit'
complete -c pivot_root -s h -l help -d 'Display help text and exit'

