# poweroff
# Autogenerated from man page /bedrock/cross/man/man8/poweroff.8
complete -c poweroff -s n -d 'Don\'t sync before reboot or halt'
complete -c poweroff -s f -d 'Force halt or reboot, don\'t call init 8.  This is dangerous !'
complete -c poweroff -s d -d 'Do not write the wtmp record'
complete -c poweroff -s w -d 'Just write the wtmp record'
complete -c poweroff -s B -d 'Just write the wtmp record, but for a boot'
complete -c poweroff -s h -d 'to put hard drives in standby mode'
complete -c poweroff -s i -d 'to shut down network interfaces'

