# printf
# Autogenerated from man page /bedrock/cross/man/man1/printf.1
complete -c printf -l help -d 'display this help and exit'
complete -c printf -l version -d 'output version information and exit '

