# prune
# Autogenerated from man page /bedrock/cross/man/man1/prune.1
complete -c prune -s n -d 'Specifies name of node to prune'
complete -c prune -s N -d 'Specifies attribute that will be set (or changed if it exists) for any pruned…'
complete -c prune -s v -d 'Verbose output'
complete -c prune -s h -s '?' -d 'Prints the usage and exits.  EXAMPLES An input graph test. gv of the form'

