# ps2pdf
# Autogenerated from man page /bedrock/cross/man/man1/ps2pdf.1
complete -c ps2pdf -o dCompatibilityLevel -d 'switch in the command line'
complete -c ps2pdf -o dPDFSETTINGS -d 'figure. ps proof. pdf'
complete -c ps2pdf -s t -d ps2pdf

