# qtchooser
# Autogenerated from man page /bedrock/cross/man/man1/qtchooser.1
complete -c qtchooser -o list-versions
complete -c qtchooser -o print-env
complete -c qtchooser -o qt
complete -c qtchooser -o run-tool

