# rdma-dev
# Autogenerated from man page /bedrock/cross/man/man8/rdma-dev.8
complete -c rdma-dev -s V
complete -c rdma-dev -s d -d 'rdma dev show [  DEV  ] rdma dev set [  DEV  ] name NEWNAME rdma dev set [  D…'

