# rdma-resource
# Autogenerated from man page /bedrock/cross/man/man8/rdma-resource.8
complete -c rdma-resource -s j
complete -c rdma-resource -s d -d 'rdma resource show [  DEV/PORT_INDEX  ] rdma resource help'

