# reboot
# Autogenerated from man page /bedrock/cross/man/man8/reboot.8
complete -c reboot -s n -d 'Don\'t sync before reboot or halt'
complete -c reboot -s f -d 'Force halt or reboot, don\'t call init 8.  This is dangerous !'
complete -c reboot -s d -d 'Do not write the wtmp record'
complete -c reboot -s w -d 'Just write the wtmp record'
complete -c reboot -s B -d 'Just write the wtmp record, but for a boot'
complete -c reboot -s h -d 'to put hard drives in standby mode'
complete -c reboot -s i -d 'to shut down network interfaces'

