# resize
# Autogenerated from man page /bedrock/cross/man/man8/resize.f2fs.8
complete -c resize -s t -d 'Specify the size in sectors'
complete -c resize -s d -d 'Specify the level of debugging options'

