# rev
# Autogenerated from man page /bedrock/cross/man/man1/rev.1
complete -c rev -s V -l version -d 'Display version information and exit'
complete -c rev -s h -l help -d 'Display help text and exit'

