# secret-tool
# Autogenerated from man page /bedrock/cross/man/man1/secret-tool.1
complete -c secret-tool -l label -d 'argument.  This label will be displayed in the password manager'
complete -c secret-tool -l all
complete -c secret-tool -l unlock

