# setleds
# Autogenerated from man page /bedrock/cross/man/man1/setleds.1
complete -c setleds -o num -d 'Clear or set NumLock'
complete -c setleds -o caps -d 'Clear or set CapsLock'
complete -c setleds -o scroll -d 'Clear or set ScrollLock'

