# shutdown
# Autogenerated from man page /bedrock/cross/man/man8/shutdown.8
complete -c shutdown -s c -d 'Cancel an ongoing shutdown'
complete -c shutdown -s f -d 'Enable fast booting; skip fsck 8 on next boot'
complete -c shutdown -s F -d 'Force run of fsck 8 on next boot'
complete -c shutdown -s h -d 'Halt the system'
complete -c shutdown -s k -d 'Don\'t really shutdown; only send the warning messages to everybody'
complete -c shutdown -s P -d 'Poweroff the system'
complete -c shutdown -s r -d 'Reboot the system.  now Shutdown without further waiting'
complete -c shutdown -s t -d 'to wait secs seconds between SIGKILL and SIGTERM on shutdown is silently igno…'
complete -c shutdown -s a -d 'Use /etc/shutdown. allow'
complete -c shutdown -s H -d 'Drop into boot monitor'
complete -c shutdown -s n -d 'Don\'t call init 8'

