# smproxy
# Autogenerated from man page /bedrock/cross/man/man1/smproxy.1
complete -c smproxy -o clientId -d 'Specifies the session ID used by smproxy in the previous session'
complete -c smproxy -o restore -d 'Specifies the file used by smproxy to save state in the previous session'
complete -c smproxy -o version -d 'Prints the program version and exits.  DESCRIPTION'

