# sum
# Autogenerated from man page /bedrock/cross/man/man1/sum.1
complete -c sum -s r -d 'use BSD sum algorithm, use 1K blocks'
complete -c sum -s s -l sysv -d 'use System V sum algorithm, use 512 bytes blocks'
complete -c sum -l help -d 'display this help and exit'
complete -c sum -l version -d 'output version information and exit AUTHOR Written by Kayvan Aghaiepour and D…'

