# sv
# Autogenerated from man page /bedrock/cross/man/man8/sv.8
complete -c sv -s v -d 'If the  command is up, down, term, once, cont, or exit, then wait up to 7 sec…'
complete -c sv -s w -d 'Override the default timeout of 7 seconds with sec seconds'

