# svlogd
# Autogenerated from man page /bedrock/cross/man/man8/svlogd.8
complete -c svlogd -s t -d timestamp
complete -c svlogd -o tt -d timestamp
complete -c svlogd -o ttt -d timestamp
complete -c svlogd -s r -d 'replace.   c must be a single character'
complete -c svlogd -s R -d 'replace charset'
complete -c svlogd -s l -d 'line length'
complete -c svlogd -s b -d 'buffer size'
complete -c svlogd -s v -d 'verbose.  Print verbose messages to standard error'

