# switch_root
# Autogenerated from man page /bedrock/cross/man/man8/switch_root.8
complete -c switch_root -s h -l help -d 'Display help text and exit'
complete -c switch_root -s V -l version -d 'Display version information and exit'

