# synclient
# Autogenerated from man page /bedrock/cross/man/man1/synclient.1
complete -c synclient -s l -d 'List current user settings.  This is the default if no option is given'
complete -c synclient -s V -d 'Print version number and exit'
complete -c synclient -s '?' -d 'Show the help message'

