# system-config-printer
# Autogenerated from man page /bedrock/cross/man/man1/system-config-printer.1
complete -c system-config-printer -l help -d 'Display a short usage message'
complete -c system-config-printer -l show-jobs -d 'Show the named print queue'
complete -c system-config-printer -l debug -d 'Enable debugging output'

