# tbl
# Autogenerated from man page /bedrock/cross/man/man1/tbl.1
complete -c tbl -s C -d 'Enable compatibility mode to recognize  . TS and  '
complete -c tbl -s t -d 'option of groff'
complete -c tbl -s v -d 'Print the version number'
complete -c tbl -o ms -d 'macros which provide this functionality if a table starts with '

