# tifficc
# Autogenerated from man page /bedrock/cross/man/man1/tifficc.1
complete -c tifficc -s a -d 'Handle channels > 4 as alpha'
complete -c tifficc -s b -d 'Black point compensation'
complete -c tifficc -s c -d 'Precalculates transform'
complete -c tifficc -s e -d 'Embed destination profile'
complete -c tifficc -s g -d 'Marks out-of-gamut colors on softproof'
complete -c tifficc -s h -d 'Show summary of options and examples'
complete -c tifficc -o iprofile -d 'Input profile (defaults to sRGB)'
complete -c tifficc -s k -d 'Ink-limiting in % (CMYK only)'
complete -c tifficc -o lprofile -d 'Transform by device-link profile'
complete -c tifficc -s m -d 'SoftProof intent'
complete -c tifficc -s n -d 'Ignore embedded profile on input'
complete -c tifficc -s p -d 'Soft proof profile'
complete -c tifficc -s o -d 'p Output profile (defaults to sRGB)'
complete -c tifficc -s s -d 'Save embedded profile as <new profile>'
complete -c tifficc -s t -d 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute)'
complete -c tifficc -s v -d Verbose
complete -c tifficc -s w -d 'Wide output (generates 16 bps tiff)'
complete -c tifficc -s i -d 'Input profile (defaults to sRGB)'
complete -c tifficc -s l -d 'Transform by device-link profile'

