# tipc-link
# Autogenerated from man page /bedrock/cross/man/man8/tipc-link.8
complete -c tipc-link -s h -l help -d 'Show help about last valid command'
complete -c tipc-link -s j -o json -d 'Output results in JavaScript Object Notation (JSON)'
complete -c tipc-link -s p -o pretty -d 'The default JSON format is compact and more efficient to parse but hard for m…'

