# transmission-create
# Autogenerated from man page /bedrock/cross/man/man1/transmission-create.1
complete -c transmission-create -s h -d 'Show a short help page and exit'
complete -c transmission-create -s o -d 'Save the generated . torrent to this filename'
complete -c transmission-create -s p -d 'Flag the torrent as intended for use on private trackers'
complete -c transmission-create -s c -d 'Add a comment to the torrent file'
complete -c transmission-create -s s -d 'Set how many KiB each piece should be, overriding the preferred default'
complete -c transmission-create -s t -d 'Add a tracker\'s announce URL to the . torrent'

