# transmission-edit
# Autogenerated from man page /bedrock/cross/man/man1/transmission-edit.1
complete -c transmission-edit -s h -d 'Show a short help page and exit'
complete -c transmission-edit -s a -d 'Add an announce URL to the torrent\'s announce-list if it\'s not already in the…'
complete -c transmission-edit -s d -d 'Remove an announce URL from the torrent\'s announce-list'
complete -c transmission-edit -s r -d 'Substring search-and-replace inside a torrent\'s announce URLs'

