# traptoemail
# Autogenerated from man page /bedrock/cross/man/man1/traptoemail.1
complete -c traptoemail -s f -d 'sender address, defaults to "root"'
complete -c traptoemail -s s -d 'SMTP server, defaults to "localhost"'

