# ts_verify
# Autogenerated from man page /bedrock/cross/man/man1/ts_verify.1
complete -c ts_verify -s i -l idev -d 'Explicitly choose the original input event device for tslib to use'
complete -c ts_verify -s h -l help

