# udevd
# Autogenerated from man page /bedrock/cross/man/man8/udevd.8
complete -c udevd -s d -l daemon -d 'Detach and run in the background'
complete -c udevd -s D -l debug -d 'Print debug messages to standard error'
complete -c udevd -s c -l children-max -d 'Limit the number of events executed in parallel'
complete -c udevd -s e -l exec-delay -d 'Delay the execution of RUN instructions by the given number of seconds'
complete -c udevd -s t -l event-timeout -d 'Set the number of seconds to wait for events to finish'
complete -c udevd -s N -l resolve-names -d 'Specify when udevd should resolve names of users and groups'
complete -c udevd -s h -l help

