# unlink
# Autogenerated from man page /bedrock/cross/man/man1/unlink.1
complete -c unlink -l help -d 'display this help and exit'
complete -c unlink -l version -d 'output version information and exit AUTHOR Written by Michael Stone'

