# users
# Autogenerated from man page /bedrock/cross/man/man1/users.1
complete -c users -l help -d 'display this help and exit'
complete -c users -l version -d 'output version information and exit AUTHOR Written by Joseph Arceneaux and Da…'

