# uxterm
# Autogenerated from man page /bedrock/cross/man/man1/uxterm.1
complete -c uxterm -o class -d and
complete -c uxterm -o u8 -d 'options should not be specified because they are used by the wrapper'

