# view
# Autogenerated from man page /bedrock/cross/man/man1/view.1
complete -c view -s c -d 'Execute  cmd immediately after starting the edit session'
complete -c view -s e -d 'Start editing in ex mode, as if the command name were R ex '
complete -c view -s l -d 'Start editing with the lisp and showmatch options set'
complete -c view -s R -d 'Start editing in read\\(hyonly mode, as if the command name was R view , or th…'
complete -c view -s r -d 'Recover the specified files, or, if no files are specified, list the files th…'
complete -c view -s S -d 'Run with the  secure edit option set, disallowing all access to external prog…'
complete -c view -s s -d 'Enter batch mode; applicable only to  ex edit sessions'
complete -c view -s t -d 'Start editing at the specified tag.  (See R ctags (1))'
complete -c view -s w -d 'Set the initial window size to the specified number of lines'
complete -c view -s v -d 'Start editing in vi mode, as if the command name was vi or view '

