# w3mman
# Autogenerated from man page /bedrock/cross/man/man1/w3mman.1
complete -c w3mman -s M -d 'Specify    path as alternative MANPATH to use'
complete -c w3mman -s k -d 'Specify keyword'
complete -c w3mman -s l -d 'Specify a file.  ENVIRONMENT Two variables are available for debugging'

