# wew
# Autogenerated from man page /bedrock/cross/man/man1/wew.1
complete -c wew -s l -d 'List event mask values'
complete -c wew -s m -d 'Set event mask to mask (defaults to XCB_EVENT_MASK_ENTER_NOTIFY) El EVENT VAL…'

