# x11perfcomp
# Autogenerated from man page /bedrock/cross/man/man1/x11perfcomp.1
complete -c x11perfcomp -s r -d 'Specifies that the output should also include relative server performance'
complete -c x11perfcomp -o ro -d 'Specifies that the output should include only relative server performance'
complete -c x11perfcomp -s l -d 'Specifies a label file to use'

