# xbps-dgraph
# Autogenerated from man page /bedrock/cross/man/man1/xbps-dgraph.1
complete -c xbps-dgraph -s C -d 'Specifies a path to the XBPS configuration directory'
complete -c xbps-dgraph -s c -d 'Specifies a path to the graph configuration file, to modify the settings of t…'
complete -c xbps-dgraph -s d -d 'Enables extra debugging shown to stderr'
complete -c xbps-dgraph -s h -d 'Show the help message'
complete -c xbps-dgraph -s M -d 'For remote repositories, the data is fetched and stored in memory for the cur…'
complete -c xbps-dgraph -s R -d 'Enable repository mode'
complete -c xbps-dgraph -s r -d 'Specifies a full path for the target root directory'
complete -c xbps-dgraph -s V -d 'Show the version information'
complete -c xbps-dgraph -s g -d 'Generates a graph configuration file in the current working directory'
complete -c xbps-dgraph -s f -d 'Generates a full dependency graph of the target package'
complete -c xbps-dgraph -s m -d 'Generates a metadata graph of the target package'

