# xbps-rindex
# Autogenerated from man page /bedrock/cross/man/man1/xbps-rindex.1
complete -c xbps-rindex -s d -d 'Enables extra debugging shown to stderr'
complete -c xbps-rindex -l compression -d 'Set the repodata compression format.  If unset, defaults to zstd'
complete -c xbps-rindex -s C -d 'Check not only for file existence but for the correct file hash while cleaning'
complete -c xbps-rindex -s f -d 'Forcefully register binary package into the local repository, overwriting exi…'
complete -c xbps-rindex -s h -d 'Show the help message'
complete -c xbps-rindex -s V -d 'Show the version information'

