# xbps-alternatives
# Autogenerated from man page /bedrock/cross/man/man1/xbps-alternatives.1
complete -c xbps-alternatives -s C -d 'Specifies a path to the XBPS configuration directory'
complete -c xbps-alternatives -s d -d 'Enables extra debugging shown to stderr'
complete -c xbps-alternatives -s g -d 'Alternative group name to match.  To be used with the set mode'
complete -c xbps-alternatives -s h -d 'Show the help message'
complete -c xbps-alternatives -s r -d 'Specifies a full path for the target root directory'
complete -c xbps-alternatives -s v -d 'Enables verbose messages'
complete -c xbps-alternatives -s V -d 'Show the version information'
complete -c xbps-alternatives -s l -d 'Lists all current alternative groups or only from PKG, or just a specific gro…'
complete -c xbps-alternatives -s s -d 'Set alternative groups specified by PKG or just a specific group, if the g Fl…'

