# xbps-fbulk
# Autogenerated from man page /bedrock/cross/man/man1/xbps-fbulk.1
complete -c xbps-fbulk -s a -d 'Set a different target architecture, useful for cross compiling'
complete -c xbps-fbulk -s j -d 'Set number of parallel builds running at the same time.  By default set to 1'
complete -c xbps-fbulk -s l -d 'Set the log directory.  By default set to `log. <pid>`'
complete -c xbps-fbulk -s d -d 'Enables extra debugging shown to stderr'
complete -c xbps-fbulk -s h -d 'Show the help message'
complete -c xbps-fbulk -s v -d 'Enables verbose messages'
complete -c xbps-fbulk -s V -d 'Show the version information'

