# xbps-uchroot
# Autogenerated from man page /bedrock/cross/man/man1/xbps-uchroot.1
complete -c xbps-uchroot -s b -d 'Bind mounts src into CHROOTDIR/dest'
complete -c xbps-uchroot -s O -d 'Setups a temporary directory and then creates an overlay layer (via overlayfs…'
complete -c xbps-uchroot -s o -d 'Arguments passed to the tmpfs mount, if the O and t options are specified'
complete -c xbps-uchroot -s t -d 'This makes the temporary directory to be mounted in tmpfs, so that everything…'

