# xbps-reconfigure
# Autogenerated from man page /bedrock/cross/man/man1/xbps-reconfigure.1
complete -c xbps-reconfigure -s a -d 'Configures all packages'
complete -c xbps-reconfigure -s C -d 'Specifies a path to the XBPS configuration directory'
complete -c xbps-reconfigure -s d -d 'Enables extra debugging shown to stderr'
complete -c xbps-reconfigure -s f -d 'Forcefully reconfigure package even if it was configured previously'
complete -c xbps-reconfigure -s h -d 'Show the help message'
complete -c xbps-reconfigure -s i -d 'Ignore PKG when configuring all packages with a, Fl -all'
complete -c xbps-reconfigure -s r -d 'Specifies a path for the target root directory'
complete -c xbps-reconfigure -s v -d 'Enables verbose messages'
complete -c xbps-reconfigure -s V -d 'Show the version information.  El FILES -tag -width /var/db/xbps/'

