# xbps-digest
# Autogenerated from man page /bedrock/cross/man/man1/xbps-digest.1
complete -c xbps-digest -s m -d 'Sets the message digest mode.  Supported: sha256'
complete -c xbps-digest -s h -d 'Show the help message'
complete -c xbps-digest -s V -d 'Show the version information'

