# xcalc
# Autogenerated from man page /bedrock/cross/man/man1/xcalc.1
complete -c xcalc -o stipple -d 'This option indicates that the background of the calculator should be drawn u…'
complete -c xcalc -o rpn -d 'This option indicates that Reverse Polish Notation should be used'

