# xcmsdb
# Autogenerated from man page /usr/share/man/man1/xcmsdb.1
complete -c xcmsdb -o format -d 'Specifies the property format (32, 16, or 8 bits per entry) for the XDCCC_LIN…'
complete -c xcmsdb -o version -d 'This option prints the program version and exits'

