# xcutsel
# Autogenerated from man page /bedrock/cross/man/man1/xcutsel.1
complete -c xcutsel -o selection -d 'This option specifies the name of the selection to use'
complete -c xcutsel -o cutbuffer -d 'This option specifies the cut buffer to use.   The default is cut buffer 0'

