# xfs_scrub_all
# Autogenerated from man page /bedrock/cross/man/man8/xfs_scrub_all.8
complete -c xfs_scrub_all -s h -d 'Display help'
complete -c xfs_scrub_all -s V -d 'Prints the version number and exits'

