# xfs_info
# Autogenerated from man page /bedrock/cross/man/man8/xfs_info.8
complete -c xfs_info -s t -d 'Specifies an alternate mount table file (default is  /proc/mounts if it exist…'
complete -c xfs_info -s V -d 'Prints the version number and exits'

