# xlsclients
# Autogenerated from man page /bedrock/cross/man/man1/xlsclients.1
complete -c xlsclients -o display -d 'This option specifies the X server to contact'
complete -c xlsclients -s a -d 'This option indicates that clients on all screens should be listed'
complete -c xlsclients -s l -d 'List in long format, giving the window name, icon name, and class hints in ad…'
complete -c xlsclients -s m -d 'This option specifies the maximum number of characters in a command to print …'
complete -c xlsclients -o version -d 'Print the program version and exit'

