# xsane
# Autogenerated from man page /bedrock/cross/man/man1/xsane.1
complete -c xsane -l version -d or
complete -c xsane -s v -d 'flag is given xsane prints a version information, some information about gtk+…'
complete -c xsane -l license -d or
complete -c xsane -s l -d 'flag is given xsane prints license information and exits'
complete -c xsane -l device-settings -d or
complete -c xsane -s d -d 'flag reads the next option as default filename for device settings'
complete -c xsane -l viewer -d or
complete -c xsane -s V -d 'flag forces xsane to start in viewer mode'
complete -c xsane -l save -d or
complete -c xsane -s s -d 'flag forces xsane to start in save mode'
complete -c xsane -l copy -d or
complete -c xsane -s c -d 'flag forces xsane to start in copy mode'
complete -c xsane -l fax -d or
complete -c xsane -s f -d 'flag forces xsane to start in fax mode'
complete -c xsane -l mail -d or
complete -c xsane -s m -d 'flag forces xsane to start in mail mode'
complete -c xsane -l no-mode-selection -d or
complete -c xsane -s n -d 'flag disables the menu for xsane mode selection (viewer, save, copy, fax, mai…'
complete -c xsane -l Fixed -d or
complete -c xsane -s F -d 'flag is given then xsane uses a fixed, non resizable main window'
complete -c xsane -l Resizable -d or
complete -c xsane -s R -d 'flag is given then xsane uses a scrolled and resizable main window'
complete -c xsane -l print-filenames -d or
complete -c xsane -s p -d 'flag is given then xsane prints the names of created files to the standard ou…'
complete -c xsane -l force-filename -d or
complete -c xsane -s N -d 'is given then xsane reads the next option as default image filename'
complete -c xsane -l display -d 'flag selects the X11 display used to present the graphical user-interface (se…'
complete -c xsane -l sync -d 'flag requests a synchronous connection with the X11 server'

