# yes
# Autogenerated from man page /bedrock/cross/man/man1/yes.1
complete -c yes -l help -d 'display this help and exit'
complete -c yes -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

