# zzz
# Autogenerated from man page /bedrock/cross/man/man8/zzz.8
complete -c zzz -s n -d 'dry-run mode'
complete -c zzz -s S -d 'Enter low-power idle mode (ACPI S1, kernel name "freeze")'
complete -c zzz -s z -d 'Enter suspend to RAM mode (ACPI S3, kernel name "mem")'
complete -c zzz -s Z -d 'Enter hibernate to disk mode (ACPI S4, kernel name "disk") and power off'
complete -c zzz -s R -d 'Enter hibernate to disk mode and reboot'
complete -c zzz -s H -d 'Enter hibernate to disk mode and suspend'

